name: simple-usage-example
core:
  auth:
    strategies: {}
    paths: []
  cloud:
    cluster: ''
    environment: 'development'
    region: ''
  port: 3002
  cors:
    enabled: true
    origins: ['http://localhost:3002']
  https:
    enabled: false
    options: {}