service:
  name: node-service-test
  version: 1.0.0
  environment: test
  port: 0 # Use random port for tests
  
  logging:
    level: error
    format: json
    silent: true # Silence logs during tests
    
  middleware:
    cors:
      enabled: false
    helmet:
      enabled: false
    auth:
      enabled: false
    rateLimit:
      enabled: false
      
  health:
    enabled: true
    path: /health
    
  shutdown:
    enabled: false # Don't handle signals in tests