name: middleware-example
core:
  auth:
    strategies: {}
    paths: []
  cloud:
    cluster: ''
    environment: 'development'
    region: ''
  port: 3004
  cors:
    enabled: true
    origins: ['http://localhost:3004']
    methods: ['GET', 'POST', 'PUT', 'DELETE']
    requestHeaders: ['Content-Type', 'Authorization']
    supportsCredentials: true
  https:
    enabled: false
    options: {}