core:
  port: 3021
  cors:
    enabled: true
    origins:
      - http://51.21.205.125
      - http://localhost:3000
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
env:
  JWT_SECRET: development
