name: Frontend CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable Corepack and install Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Debug info
        run: |
          echo "Debugging Environment Information"
          echo "-----------------------------------"
          echo "Node version: $(node -v)"
          echo "Yarn version: $(yarn -v)"
          if [ -z "$GH_PKG_PRODUCE_TOKEN" ]; then
            echo "❌ GH_PKG_PRODUCE_TOKEN is not set";
          else
            echo "✅ GH_PKG_PRODUCE_TOKEN is set";
          fi
        env:
          GH_PKG_PRODUCE_TOKEN: ${{ secrets.GH_PKG_PRODUCE_TOKEN }}

      - name: Install dependencies
        run: |
          echo "🏁 Installing dependencies..."
          yarn install
        env:
          GH_PKG_PRODUCE_TOKEN: ${{ secrets.GH_PKG_PRODUCE_TOKEN }}

      - name: Build package
        run: yarn build || (echo "❌ Build failed!" && exit 1)
        env:
          GH_PKG_PRODUCE_TOKEN: ${{ secrets.GH_PKG_PRODUCE_TOKEN }}

      - name: Check lint
        run: yarn lint || (echo "❌ Lint failed!" && exit 1)
        env:
          GH_PKG_CONSUME_TOKEN: ${{ secrets.GH_PKG_CONSUME_TOKEN }}

      - name: Check types
        run: yarn types || (echo "❌ Type checking failed!" && exit 1)
