name: Package CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check environment variables
        run: |
          echo "Debugging environment variables"
          if [ -z "$GH_PKG_PRODUCE_TOKEN" ]; then
            echo "❌ GH_PKG_PRODUCE_TOKEN is not set";
          else
            echo "✅ GH_PKG_PRODUCE_TOKEN is set";
          fi
        env:
          GH_PKG_PRODUCE_TOKEN: ${{ secrets.GH_PKG_PRODUCE_TOKEN }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: |
          pnpm install
        env:
          GH_PKG_PRODUCE_TOKEN: ${{ secrets.GH_PKG_PRODUCE_TOKEN }}

      - name: Debug environment information
        run: |
          echo "Debugging environment information"
          echo "-----------------------------------"
          echo "Node version: $(node -v)"
          echo "pnpm version: $(pnpm -v)"
        env:
          GH_PKG_PRODUCE_TOKEN: ${{ secrets.GH_PKG_PRODUCE_TOKEN }}

      - name: Install dependencies
        run: |
          echo "🏁 Installing dependencies..."
          pnpm install
        env:
          GH_PKG_PRODUCE_TOKEN: ${{ secrets.GH_PKG_PRODUCE_TOKEN }}

      - name: Build package
        run: |
          pnpm build || (echo "❌ Build failed!" && exit 1)
        env:
          GH_PKG_PRODUCE_TOKEN: ${{ secrets.GH_PKG_PRODUCE_TOKEN }}

      - name: Check lint
        run: pnpm lint || (echo "❌ Lint failed!" && exit 1)
        env:
          GH_PKG_PRODUCE_TOKEN: ${{ secrets.GH_PKG_PRODUCE_TOKEN }}

      - name: Check types
        run: |
          pnpm type:check || (echo "❌ Type checking failed!" && exit 1)
        env:
          GH_PKG_PRODUCE_TOKEN: ${{ secrets.GH_PKG_PRODUCE_TOKEN }}
